version: "3.9"

services:
  server:
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
    command: python3 start_rabbit_mq.py
  worker:
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
    command: python3 worker.py
