action_id: trunk-upgrade-available
date: 2023-08-15 22:18:47
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: .trunk/trunk.yaml
result:
  exit_code: 0
  out: "notifications:\n  - commands:\n      - run: trunk upgrade\n        title: all\n      - run: trunk upgrade check\n        title: Linters\n    id: trunk-upgrade\n    message: \" 12 linter upgrades\\n\"\n    priority: low\n    rendered: \"\\x1b[90mRun \\x1b[0m\\x1b[96mtrunk upgrade\\x1b[0m\\x1b[90m to upgrade \\x1b[0m\\x1b[90m12 linters\\n\\x1b[0m\"\n    title: Upgrades Available\nnotifications_to_delete:\n  - trunk-check-upgrade\n"
  err: ""
timestamp: 1692137927
full_timestamp:
  nanos: 540728000
  seconds: 1692137927
trunk_version: 1.13.0
action_output:
  notifications:
    - commands:
        - run: trunk upgrade
          title: all
        - run: trunk upgrade check
          title: Linters
      full_timestamp:
        nanos: 540728000
        seconds: 1692137927
      id: trunk-upgrade
      message: " 12 linter upgrades\n"
      priority: low
      rendered: "\x1b[90mRun \x1b[0m\x1b[96mtrunk upgrade\x1b[0m\x1b[90m to upgrade \x1b[0m\x1b[90m12 linters\n\x1b[0m"
      timestamp: 1692137927
      title: Upgrades Available
  notifications_to_delete:
    - trunk-check-upgrade
