from discord_analyzer.analysis.analytics_interactions_script import (
    sum_interactions_features,
)


def test_sum_interactions_features_out_length():
    interactions = [
        "thr_messages",
        "lone_messages",
        "replier",
        "replied",
        "replied",
        "mentioner",
        "mentioned",
        "reacter",
        "reacted",
    ]
    sample_input = []
    output = sum_interactions_features(cursor_list=sample_input, dict_keys=interactions)

    for action in interactions:
        # 24 hours
        assert len(output[action]) == 24


def test_sum_interactions_features_empty_input():
    interactions = [
        "thr_messages",
        "lone_messages",
        "replier",
        "replied",
        "replied",
        "mentioner",
        "mentioned",
        "reacter",
        "reacted",
    ]
    sample_input = []
    output = sum_interactions_features(cursor_list=sample_input, dict_keys=interactions)

    for action in interactions:
        assert sum(output[action]) == 0


def test_sum_interactions_features_single_input():
    interactions = [
        "thr_messages",
        "lone_messages",
        "replier",
        "replied",
        "mentioner",
        "mentioned",
        "reacter",
        "reacted",
    ]
    sample_input = [
        {
            "thr_messages": [
                0,
                0,
                5,
                107,
                0,
                1,
                0,
                0,
                0,
                0,
                4,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
            ],
            "lone_messages": [
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                80,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
            ],
            "replier": [
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                5,
                0,
            ],
            "replied": [
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
            ],
            "mentioner": [
                0,
                0,
                0,
                1,
                0,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
            ],
            "mentioned": [
                0,
                0,
                0,
                0,
                0,
                3,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
            ],
            "reacter": [
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
            ],
            "reacted": [
                50000,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                100000,
                0,
                0,
                0,
                0,
                0,
                0,
            ],
        }
    ]

    output = sum_interactions_features(cursor_list=sample_input, dict_keys=interactions)

    assert sum(output["thr_messages"]) == 117
    assert sum(output["lone_messages"]) == 80
    assert sum(output["replier"]) == 5
    assert sum(output["replied"]) == 24
    assert sum(output["mentioner"]) == 2
    assert sum(output["mentioned"]) == 3
    assert sum(output["reacter"]) == 1
    assert sum(output["reacted"]) == 150000


def test_sum_interactions_features_multiple_input():
    interactions = [
        "thr_messages",
        "lone_messages",
        "replier",
        "replied",
        "mentioner",
        "mentioned",
        "reacter",
        "reacted",
    ]
    sample_input = [
        {
            "thr_messages": [
                0,
                0,
                5,
                107,
                0,
                1,
                0,
                0,
                0,
                0,
                4,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
            ],
            "lone_messages": [
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                80,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
            ],
            "replier": [
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                5,
                0,
            ],
            "replied": [
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
            ],
            "mentioner": [
                0,
                0,
                0,
                1,
                0,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
            ],
            "mentioned": [
                0,
                0,
                0,
                0,
                0,
                3,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
            ],
            "reacter": [
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
            ],
            "reacted": [
                50000,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                100000,
                0,
                0,
                0,
                0,
                0,
                0,
            ],
        },
        {
            "thr_messages": [
                0,
                0,
                5,
                100,
                0,
                1,
                0,
                0,
                0,
                0,
                4,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
            ],
            "lone_messages": [
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                80,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
            ],
            "replier": [
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                5,
                0,
            ],
            "replied": [
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
            ],
            "mentioner": [
                0,
                0,
                0,
                1,
                0,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
            ],
            "mentioned": [
                0,
                0,
                0,
                0,
                0,
                3,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
            ],
            "reacter": [
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
            ],
            "reacted": [
                50000,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                100000,
                0,
                0,
                0,
                0,
                0,
                0,
            ],
        },
    ]

    output = sum_interactions_features(cursor_list=sample_input, dict_keys=interactions)

    assert sum(output["thr_messages"]) == 227
    assert sum(output["lone_messages"]) == 160
    assert sum(output["replier"]) == 10
    assert sum(output["replied"]) == 48
    assert sum(output["mentioner"]) == 4
    assert sum(output["mentioned"]) == 6
    assert sum(output["reacter"]) == 2
    assert sum(output["reacted"]) == 300000
